package com.everx.shared.saga.event;

public enum SagaEventType {
    SAGA_STARTED,
    QUOTE_VALIDATION_STARTED,
    STEP_COMPLETED,
    SAGA_FAILED,
    SAGA_COMPLETED,
    COMPENSATE_SALES_ORDER,
    COMPENSATE_INVENTORY_RELEASE,
    COMPENSATE_INVOICE_VOID,
    COMPENSATE_PAYMENT_REVERSAL
}
