import { ROLES, PERMISSIONS } from '../hooks/usePermissions'

export interface RolePermissionMapping {
  [role: string]: string[]
}

export const ROLE_PERMISSIONS: RolePermissionMapping = {
  // Super Admin - Has all permissions
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  // System Administrator - System-wide admin permissions
  [ROLES.SYSTEM_ADMINISTRATOR]: [
    // Core admin permissions
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_EDIT,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_ASSIGN_ROLE,
    PERMISSIONS.ROLE_VIEW,
    PERMISSIONS.ROLE_CREATE,
    PERMISSIONS.ROLE_EDIT,
    PERMISSIONS.ROLE_DELETE,
    PERMISSIONS.ROLE_ASSIGN_PERMISSION,
    
    // All module admin permissions
    PERMISSIONS.PERFORMANCE_ADMIN,
    PERMISSIONS.SECURITY_ADMIN,
    PERMISSIONS.ANALYTICS_ADMIN,
    PERMISSIONS.INTEGRATION_ADMIN,
    PERMISSIONS.CUSTOMER_SUCCESS_ADMIN,
    PERMISSIONS.WORKFLOW_ADMIN,
    PERMISSIONS.ADVANCED_FEATURES_ADMIN,
    PERMISSIONS.UX_SETTINGS_MANAGE,
    
    // All module view permissions
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.FIELDWORK_VIEW,
    PERMISSIONS.PERFORMANCE_VIEW,
    PERMISSIONS.SECURITY_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.INTEGRATION_VIEW,
    PERMISSIONS.CUSTOMER_SUCCESS_VIEW,
    PERMISSIONS.WORKFLOW_VIEW,
    PERMISSIONS.ADVANCED_FEATURES_VIEW,
    PERMISSIONS.UX_SETTINGS_VIEW,
    
    // Dashboard and data scope
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DASHBOARD_FINANCE_VIEW,
    PERMISSIONS.DASHBOARD_HR_VIEW,
    PERMISSIONS.DASHBOARD_TECH_VIEW,
    PERMISSIONS.DASHBOARD_OPERATIONS_VIEW,
    PERMISSIONS.DATA_SCOPE_ORG,
    
    // Reports and insights
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.REPORT_PERSONAL_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Admin - Traditional admin role
  [ROLES.ADMIN]: [
    // Core admin permissions
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_EDIT,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_ASSIGN_ROLE,
    PERMISSIONS.ROLE_VIEW,
    PERMISSIONS.ROLE_CREATE,
    PERMISSIONS.ROLE_EDIT,
    PERMISSIONS.ROLE_DELETE,
    PERMISSIONS.ROLE_ASSIGN_PERMISSION,
    
    // Most module permissions (excluding advanced features)
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_EDIT,
    PERMISSIONS.CRM_DELETE,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.ERP_CREATE,
    PERMISSIONS.ERP_EDIT,
    PERMISSIONS.ERP_DELETE,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE,
    PERMISSIONS.FINANCE_EDIT,
    PERMISSIONS.FINANCE_DELETE,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.HR_CREATE,
    PERMISSIONS.HR_EDIT,
    PERMISSIONS.HR_DELETE,
    PERMISSIONS.FIELDWORK_VIEW,
    PERMISSIONS.FIELDWORK_CREATE,
    PERMISSIONS.FIELDWORK_EDIT,
    PERMISSIONS.PERFORMANCE_VIEW,
    PERMISSIONS.SECURITY_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.INTEGRATION_VIEW,
    PERMISSIONS.CUSTOMER_SUCCESS_VIEW,
    PERMISSIONS.WORKFLOW_VIEW,
    
    // Dashboard and data scope
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DASHBOARD_FINANCE_VIEW,
    PERMISSIONS.DASHBOARD_HR_VIEW,
    PERMISSIONS.DASHBOARD_TECH_VIEW,
    PERMISSIONS.DASHBOARD_OPERATIONS_VIEW,
    PERMISSIONS.DATA_SCOPE_ORG,
    
    // Reports and insights
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.REPORT_PERSONAL_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Manager - Department manager
  [ROLES.MANAGER]: [
    // Core permissions
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_EDIT,
    PERMISSIONS.ROLE_VIEW,
    
    // Business module permissions
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_EDIT,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.ERP_CREATE,
    PERMISSIONS.ERP_EDIT,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE,
    PERMISSIONS.FINANCE_EDIT,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.HR_CREATE,
    PERMISSIONS.HR_EDIT,
    PERMISSIONS.FIELDWORK_VIEW,
    PERMISSIONS.FIELDWORK_CREATE,
    PERMISSIONS.FIELDWORK_EDIT,
    PERMISSIONS.PERFORMANCE_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.INTEGRATION_VIEW,
    PERMISSIONS.CUSTOMER_SUCCESS_VIEW,
    PERMISSIONS.WORKFLOW_VIEW,
    
    // Dashboard and data scope
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DASHBOARD_OPERATIONS_VIEW,
    PERMISSIONS.DATA_SCOPE_TEAM,
    
    // Reports and insights
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.REPORT_PERSONAL_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Performance Admin
  [ROLES.PERFORMANCE_ADMIN]: [
    // Core permissions
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.ROLE_VIEW,
    
    // Performance module full permissions
    PERMISSIONS.PERFORMANCE_VIEW,
    PERMISSIONS.PERFORMANCE_CREATE,
    PERMISSIONS.PERFORMANCE_EDIT,
    PERMISSIONS.PERFORMANCE_DELETE,
    PERMISSIONS.PERFORMANCE_ADMIN,
    PERMISSIONS.PERFORMANCE_ALERTS_VIEW,
    PERMISSIONS.PERFORMANCE_ALERTS_MANAGE,
    PERMISSIONS.PERFORMANCE_SLA_VIEW,
    PERMISSIONS.PERFORMANCE_SLA_MANAGE,
    PERMISSIONS.PERFORMANCE_OPTIMIZATION_VIEW,
    PERMISSIONS.PERFORMANCE_OPTIMIZATION_MANAGE,
    
    // Basic view permissions for other modules
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.INTEGRATION_VIEW,
    
    // Dashboard and reports
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DATA_SCOPE_TEAM,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Performance Analyst
  [ROLES.PERFORMANCE_ANALYST]: [
    // Performance module view permissions
    PERMISSIONS.PERFORMANCE_VIEW,
    PERMISSIONS.PERFORMANCE_CREATE,
    PERMISSIONS.PERFORMANCE_EDIT,
    PERMISSIONS.PERFORMANCE_ALERTS_VIEW,
    PERMISSIONS.PERFORMANCE_SLA_VIEW,
    PERMISSIONS.PERFORMANCE_OPTIMIZATION_VIEW,
    
    // Basic view permissions for other modules
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    
    // Dashboard and reports
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DATA_SCOPE_TEAM,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Security Admin
  [ROLES.SECURITY_ADMIN]: [
    // Core permissions
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_EDIT,
    PERMISSIONS.ROLE_VIEW,
    
    // Security module full permissions
    PERMISSIONS.SECURITY_VIEW,
    PERMISSIONS.SECURITY_CREATE,
    PERMISSIONS.SECURITY_EDIT,
    PERMISSIONS.SECURITY_DELETE,
    PERMISSIONS.SECURITY_ADMIN,
    PERMISSIONS.SECURITY_2FA_MANAGE,
    PERMISSIONS.SECURITY_SSO_MANAGE,
    PERMISSIONS.SECURITY_SESSIONS_VIEW,
    PERMISSIONS.SECURITY_SESSIONS_MANAGE,
    PERMISSIONS.SECURITY_POLICIES_VIEW,
    PERMISSIONS.SECURITY_POLICIES_MANAGE,
    PERMISSIONS.SECURITY_AUDIT_VIEW,
    PERMISSIONS.SECURITY_AUDIT_MANAGE,
    PERMISSIONS.SECURITY_INCIDENTS_VIEW,
    PERMISSIONS.SECURITY_INCIDENTS_MANAGE,
    PERMISSIONS.SECURITY_COMPLIANCE_VIEW,
    PERMISSIONS.SECURITY_COMPLIANCE_MANAGE,
    PERMISSIONS.SECURITY_ROLES_VIEW,
    PERMISSIONS.SECURITY_ROLES_MANAGE,
    PERMISSIONS.SECURITY_THREATS_VIEW,
    PERMISSIONS.SECURITY_THREATS_MANAGE,
    
    // Basic view permissions for other modules
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.INTEGRATION_VIEW,
    
    // Dashboard and reports
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DATA_SCOPE_ORG,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Security Analyst
  [ROLES.SECURITY_ANALYST]: [
    // Security module view permissions
    PERMISSIONS.SECURITY_VIEW,
    PERMISSIONS.SECURITY_CREATE,
    PERMISSIONS.SECURITY_EDIT,
    PERMISSIONS.SECURITY_2FA_MANAGE,
    PERMISSIONS.SECURITY_SESSIONS_VIEW,
    PERMISSIONS.SECURITY_POLICIES_VIEW,
    PERMISSIONS.SECURITY_AUDIT_VIEW,
    PERMISSIONS.SECURITY_INCIDENTS_VIEW,
    PERMISSIONS.SECURITY_COMPLIANCE_VIEW,
    PERMISSIONS.SECURITY_ROLES_VIEW,
    PERMISSIONS.SECURITY_THREATS_VIEW,
    
    // Basic view permissions for other modules
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.INTEGRATION_VIEW,
    
    // Dashboard and reports
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DATA_SCOPE_TEAM,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Analytics Admin
  [ROLES.ANALYTICS_ADMIN]: [
    // Core permissions
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.ROLE_VIEW,
    
    // Analytics module full permissions
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_CREATE,
    PERMISSIONS.ANALYTICS_EDIT,
    PERMISSIONS.ANALYTICS_DELETE,
    PERMISSIONS.ANALYTICS_ADMIN,
    PERMISSIONS.ANALYTICS_MODELS_VIEW,
    PERMISSIONS.ANALYTICS_MODELS_MANAGE,
    PERMISSIONS.ANALYTICS_TRAINING_VIEW,
    PERMISSIONS.ANALYTICS_TRAINING_MANAGE,
    PERMISSIONS.ANALYTICS_FORECASTS_VIEW,
    PERMISSIONS.ANALYTICS_FORECASTS_MANAGE,
    PERMISSIONS.ANALYTICS_PREDICTIONS_VIEW,
    PERMISSIONS.ANALYTICS_PREDICTIONS_MANAGE,
    PERMISSIONS.ANALYTICS_INSIGHTS_VIEW,
    PERMISSIONS.ANALYTICS_INSIGHTS_MANAGE,
    PERMISSIONS.ANALYTICS_EXPERIMENTS_VIEW,
    PERMISSIONS.ANALYTICS_EXPERIMENTS_MANAGE,
    PERMISSIONS.ANALYTICS_ANOMALY_VIEW,
    PERMISSIONS.ANALYTICS_ANOMALY_MANAGE,
    
    // Basic view permissions for other modules
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.PERFORMANCE_VIEW,
    PERMISSIONS.INTEGRATION_VIEW,
    
    // Dashboard and reports
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DATA_SCOPE_TEAM,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Data Scientist
  [ROLES.DATA_SCIENTIST]: [
    // Analytics module permissions
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_CREATE,
    PERMISSIONS.ANALYTICS_EDIT,
    PERMISSIONS.ANALYTICS_MODELS_VIEW,
    PERMISSIONS.ANALYTICS_MODELS_MANAGE,
    PERMISSIONS.ANALYTICS_TRAINING_VIEW,
    PERMISSIONS.ANALYTICS_TRAINING_MANAGE,
    PERMISSIONS.ANALYTICS_FORECASTS_VIEW,
    PERMISSIONS.ANALYTICS_FORECASTS_MANAGE,
    PERMISSIONS.ANALYTICS_PREDICTIONS_VIEW,
    PERMISSIONS.ANALYTICS_PREDICTIONS_MANAGE,
    PERMISSIONS.ANALYTICS_INSIGHTS_VIEW,
    PERMISSIONS.ANALYTICS_EXPERIMENTS_VIEW,
    PERMISSIONS.ANALYTICS_EXPERIMENTS_MANAGE,
    PERMISSIONS.ANALYTICS_ANOMALY_VIEW,
    
    // Basic view permissions for other modules
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.PERFORMANCE_VIEW,
    
    // Dashboard and reports
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DATA_SCOPE_TEAM,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Integration Admin
  [ROLES.INTEGRATION_ADMIN]: [
    // Core permissions
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.ROLE_VIEW,
    
    // Integration module full permissions
    PERMISSIONS.INTEGRATION_VIEW,
    PERMISSIONS.INTEGRATION_CREATE,
    PERMISSIONS.INTEGRATION_EDIT,
    PERMISSIONS.INTEGRATION_DELETE,
    PERMISSIONS.INTEGRATION_ADMIN,
    PERMISSIONS.INTEGRATION_WEBHOOKS_VIEW,
    PERMISSIONS.INTEGRATION_WEBHOOKS_MANAGE,
    PERMISSIONS.INTEGRATION_API_VIEW,
    PERMISSIONS.INTEGRATION_API_MANAGE,
    PERMISSIONS.INTEGRATION_MAPPING_VIEW,
    PERMISSIONS.INTEGRATION_MAPPING_MANAGE,
    PERMISSIONS.INTEGRATION_MONITORING_VIEW,
    PERMISSIONS.INTEGRATION_MONITORING_MANAGE,
    PERMISSIONS.INTEGRATION_SECURITY_VIEW,
    PERMISSIONS.INTEGRATION_SECURITY_MANAGE,
    PERMISSIONS.INTEGRATION_AUDIT_VIEW,
    PERMISSIONS.INTEGRATION_AUDIT_MANAGE,
    PERMISSIONS.INTEGRATION_TESTING_VIEW,
    PERMISSIONS.INTEGRATION_TESTING_MANAGE,
    
    // Basic view permissions for other modules
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.SECURITY_VIEW,
    
    // Dashboard and reports
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DATA_SCOPE_TEAM,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Integration Specialist
  [ROLES.INTEGRATION_SPECIALIST]: [
    // Integration module permissions
    PERMISSIONS.INTEGRATION_VIEW,
    PERMISSIONS.INTEGRATION_CREATE,
    PERMISSIONS.INTEGRATION_EDIT,
    PERMISSIONS.INTEGRATION_WEBHOOKS_VIEW,
    PERMISSIONS.INTEGRATION_WEBHOOKS_MANAGE,
    PERMISSIONS.INTEGRATION_API_VIEW,
    PERMISSIONS.INTEGRATION_API_MANAGE,
    PERMISSIONS.INTEGRATION_MAPPING_VIEW,
    PERMISSIONS.INTEGRATION_MAPPING_MANAGE,
    PERMISSIONS.INTEGRATION_MONITORING_VIEW,
    PERMISSIONS.INTEGRATION_SECURITY_VIEW,
    PERMISSIONS.INTEGRATION_AUDIT_VIEW,
    PERMISSIONS.INTEGRATION_TESTING_VIEW,
    PERMISSIONS.INTEGRATION_TESTING_MANAGE,
    
    // Basic view permissions for other modules
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.HR_VIEW,
    
    // Dashboard and reports
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DATA_SCOPE_TEAM,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Customer Success Manager
  [ROLES.CUSTOMER_SUCCESS_MANAGER]: [
    // Customer Success module permissions
    PERMISSIONS.CUSTOMER_SUCCESS_VIEW,
    PERMISSIONS.CUSTOMER_SUCCESS_CREATE,
    PERMISSIONS.CUSTOMER_SUCCESS_EDIT,
    PERMISSIONS.CUSTOMER_SUCCESS_DELETE,
    PERMISSIONS.CUSTOMER_SUCCESS_ADMIN,
    
    // Related business module permissions
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_EDIT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.WORKFLOW_VIEW,
    
    // Dashboard and reports
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DATA_SCOPE_TEAM,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Workflow Designer
  [ROLES.WORKFLOW_DESIGNER]: [
    // Workflow module permissions
    PERMISSIONS.WORKFLOW_VIEW,
    PERMISSIONS.WORKFLOW_CREATE,
    PERMISSIONS.WORKFLOW_EDIT,
    PERMISSIONS.WORKFLOW_DELETE,
    PERMISSIONS.WORKFLOW_ADMIN,
    PERMISSIONS.WORKFLOW_DESIGNER_VIEW,
    PERMISSIONS.WORKFLOW_DESIGNER_MANAGE,
    
    // Related module permissions
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.INTEGRATION_VIEW,
    
    // Dashboard and reports
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DATA_SCOPE_TEAM,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // UX Designer
  [ROLES.UX_DESIGNER]: [
    // UX Enhancement permissions
    PERMISSIONS.UX_SETTINGS_VIEW,
    PERMISSIONS.UX_SETTINGS_MANAGE,
    PERMISSIONS.UX_ANALYTICS_VIEW,
    PERMISSIONS.UX_ANALYTICS_MANAGE,
    PERMISSIONS.UX_PERSONALIZATION_VIEW,
    PERMISSIONS.UX_PERSONALIZATION_MANAGE,
    PERMISSIONS.ADVANCED_FEATURES_VIEW,
    PERMISSIONS.ADVANCED_FEATURES_CREATE,
    PERMISSIONS.ADVANCED_FEATURES_EDIT,
    
    // Basic view permissions for other modules
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.HR_VIEW,
    
    // Dashboard and reports
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DATA_SCOPE_TEAM,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Sales Manager
  [ROLES.SALES_MANAGER]: [
    // Sales focused permissions
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_EDIT,
    PERMISSIONS.CRM_DELETE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.CUSTOMER_SUCCESS_VIEW,
    PERMISSIONS.WORKFLOW_VIEW,
    
    // Dashboard and data scope
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DASHBOARD_SALES,
    PERMISSIONS.DATA_SCOPE_TEAM,
    
    // Reports and insights
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.REPORT_PERSONAL_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Sales Representative
  [ROLES.SALES_REP]: [
    // Basic CRM permissions
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_EDIT,
    
    // Dashboard and data scope
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_MY_WORK,
    PERMISSIONS.DATA_SCOPE_OWN,
    
    // Reports and insights
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_PERSONAL_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Finance
  [ROLES.FINANCE]: [
    // Finance module permissions
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE,
    PERMISSIONS.FINANCE_EDIT,
    PERMISSIONS.FINANCE_DELETE,
    
    // Related permissions
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    
    // Dashboard and data scope
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DASHBOARD_FINANCE_VIEW,
    PERMISSIONS.DATA_SCOPE_TEAM,
    
    // Reports and insights
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.REPORT_PERSONAL_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // HR
  [ROLES.HR]: [
    // HR module permissions
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.HR_CREATE,
    PERMISSIONS.HR_EDIT,
    PERMISSIONS.HR_DELETE,
    PERMISSIONS.HR_EMPLOYEE_VIEW,
    PERMISSIONS.HR_EMPLOYEE_CREATE,
    PERMISSIONS.HR_EMPLOYEE_EDIT,
    PERMISSIONS.HR_EMPLOYEE_DELETE,
    PERMISSIONS.HR_DEPARTMENT_VIEW,
    PERMISSIONS.HR_DEPARTMENT_CREATE,
    PERMISSIONS.HR_DEPARTMENT_EDIT,
    PERMISSIONS.HR_DEPARTMENT_DELETE,
    PERMISSIONS.HR_POSITION_VIEW,
    PERMISSIONS.HR_POSITION_CREATE,
    PERMISSIONS.HR_POSITION_EDIT,
    PERMISSIONS.HR_POSITION_DELETE,
    PERMISSIONS.HR_LEAVE_REQUEST_VIEW,
    PERMISSIONS.HR_LEAVE_REQUEST_CREATE,
    PERMISSIONS.HR_LEAVE_REQUEST_APPROVE,
    PERMISSIONS.HR_TIMESHEET_VIEW,
    PERMISSIONS.HR_TIMESHEET_CREATE,
    PERMISSIONS.HR_TIMESHEET_APPROVE,
    PERMISSIONS.HR_REIMBURSEMENT_VIEW,
    PERMISSIONS.HR_REIMBURSEMENT_CREATE,
    PERMISSIONS.HR_REIMBURSEMENT_APPROVE,
    PERMISSIONS.HR_PAYROLL_RUN_VIEW,
    PERMISSIONS.HR_PAYROLL_RUN_CREATE,
    PERMISSIONS.HR_PAYROLL_RUN_EDIT,
    PERMISSIONS.HR_PAYROLL_RUN_DELETE,
    PERMISSIONS.HR_PAYROLL_PROFILE_VIEW,
    PERMISSIONS.HR_PAYROLL_PROFILE_CREATE,
    PERMISSIONS.HR_PAYROLL_PROFILE_EDIT,
    PERMISSIONS.HR_PAYROLL_PROFILE_DELETE,
    
    // Related permissions
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.SECURITY_VIEW,
    
    // Dashboard and data scope
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_TEAM_VIEW,
    PERMISSIONS.DASHBOARD_HR_VIEW,
    PERMISSIONS.DATA_SCOPE_TEAM,
    
    // Reports and insights
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_TEAM_VIEW,
    PERMISSIONS.REPORT_PERSONAL_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Service Technician
  [ROLES.SERVICE_TECH]: [
    // Fieldwork permissions
    PERMISSIONS.FIELDWORK_VIEW,
    PERMISSIONS.FIELDWORK_CREATE,
    PERMISSIONS.FIELDWORK_EDIT,
    
    // Basic CRM permissions
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_EDIT,
    
    // Dashboard and data scope
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_FIELDWORK,
    PERMISSIONS.DATA_SCOPE_OWN,
    
    // Reports and insights
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_PERSONAL_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Employee
  [ROLES.EMPLOYEE]: [
    // Basic permissions
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.HR_LEAVE_REQUEST_CREATE,
    PERMISSIONS.HR_TIMESHEET_CREATE,
    
    // Dashboard and data scope
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DASHBOARD_EMPLOYEE,
    PERMISSIONS.DATA_SCOPE_OWN,
    
    // Reports and insights
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_PERSONAL_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Viewer
  [ROLES.VIEWER]: [
    // View-only permissions
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.ERP_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.FIELDWORK_VIEW,
    PERMISSIONS.PERFORMANCE_VIEW,
    PERMISSIONS.SECURITY_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.INTEGRATION_VIEW,
    PERMISSIONS.CUSTOMER_SUCCESS_VIEW,
    PERMISSIONS.WORKFLOW_VIEW,
    PERMISSIONS.ADVANCED_FEATURES_VIEW,
    
    // Dashboard and data scope
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.DATA_SCOPE_OWN,
    
    // Reports and insights
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_PERSONAL_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
  ],

  // Read Only - Most restricted role
  [ROLES.READ_ONLY]: [
    // Minimal view permissions
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_SELF_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_PERSONAL_VIEW,
    PERMISSIONS.INSIGHTS_VIEW,
    PERMISSIONS.DATA_SCOPE_OWN,
  ],
}

// Helper function to get permissions for a role
export function getRolePermissions(role: string): string[] {
  return ROLE_PERMISSIONS[role] || []
}

// Helper function to check if a role has a specific permission
export function roleHasPermission(role: string, permission: string): boolean {
  const permissions = getRolePermissions(role)
  return permissions.includes(permission)
}

// Helper function to get all roles that have a specific permission
export function getRolesWithPermission(permission: string): string[] {
  return Object.keys(ROLE_PERMISSIONS).filter(role => 
    ROLE_PERMISSIONS[role].includes(permission)
  )
}
