spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/everx_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:}
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

logging:
  level:
    root: INFO
    com.everx: DEBUG
